services:
  compyshop_bot:
    container_name: compyshop_bot
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    env_file:
      - ./.env
    depends_on:
      - compyshop_db
    restart: unless-stopped
  compyshop_db:
    container_name: compyshop_db
    image: postgres:15.1-bullseye
    volumes:
      - ./db/pgdata:/var/lib/postgresql/data/pgdata
    env_file:
      - ./.env
    ports:
      - 5432:5432
    restart: unless-stopped